/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import business.employee;
import javax.swing.JOptionPane;
import java.sql.Date;
import data.EmployeeDB;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author prabu
 */
public class EmployeeUI extends javax.swing.JFrame {
    private EmployeeDB sDB;
    private DefaultTableModel tblModel;
    /**
     * Creates new form StudentUI
     */
    public EmployeeUI() {
        initComponents();
        setLocationRelativeTo(this);
        sDB=new EmployeeDB();
        tblModel=new DefaultTableModel();
        tblStudent.setModel(tblModel);
        tblModel.addColumn("Student ID");
        tblModel.addColumn("First Name");
        tblModel.addColumn("last Name");
        tblModel.addColumn("Gender");
        tblModel.addColumn("designations");
        tblModel.addColumn("departments");
        tblModel.addColumn("Date of Birth");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblStudentID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        cmbCourse = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        btnGetAll = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setTitle("employee");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        lblStudentID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStudentID.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentID.setText("employee ID");
        jPanel1.add(lblStudentID);
        lblStudentID.setBounds(107, 50, 100, 17);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");
        jPanel1.add(lblFirstName);
        lblFirstName.setBounds(300, 50, 100, 17);

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");
        jPanel1.add(lblLastName);
        lblLastName.setBounds(473, 50, 100, 17);

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender");
        jPanel1.add(lblGender);
        lblGender.setBounds(120, 120, 50, 17);

        lblCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setText("designations");
        jPanel1.add(lblCourse);
        lblCourse.setBounds(290, 120, 110, 17);

        txtStudentID.setToolTipText("4 digit number");
        jPanel1.add(txtStudentID);
        txtStudentID.setBounds(80, 70, 160, 30);
        jPanel1.add(txtFirstName);
        txtFirstName.setBounds(260, 70, 160, 30);
        jPanel1.add(txtLastName);
        txtLastName.setBounds(450, 70, 160, 30);

        buttonGroup1.add(rdoMale);
        rdoMale.setForeground(new java.awt.Color(255, 255, 255));
        rdoMale.setText("Male");
        jPanel1.add(rdoMale);
        rdoMale.setBounds(60, 140, 80, 23);

        buttonGroup1.add(rdoFemale);
        rdoFemale.setForeground(new java.awt.Color(255, 255, 255));
        rdoFemale.setText("Female");
        jPanel1.add(rdoFemale);
        rdoFemale.setBounds(160, 140, 80, 23);

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accountant", "It assistant", "Student counciller", "Branch manager", " " }));
        cmbCourse.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmbCourseAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCourse);
        cmbCourse.setBounds(260, 140, 160, 30);

        btnOK.setText("Add");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK);
        btnOK.setBounds(70, 280, 76, 23);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(560, 460, 75, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date of Birth");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 120, 110, 17);
        jPanel1.add(txtDOB);
        txtDOB.setBounds(450, 140, 160, 30);

        btnGetAll.setText("Get All");
        btnGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetAll);
        btnGetAll.setBounds(170, 280, 75, 23);

        btnFind.setText("search");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind);
        btnFind.setBounds(390, 280, 76, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(500, 280, 75, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(280, 280, 75, 23);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStudent);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(80, 330, 534, 114);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("departments");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 190, 140, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT department", "HR department", "financial department", "management department" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(70, 210, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/img/0x0.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 620, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
       if(checkvalidation()){
            int sID=Integer.valueOf(txtStudentID.getText());
        String firstName=txtFirstName.getText();
        String lastName=txtLastName.getText();
        String gender="";
        if(rdoMale.isSelected()){
            gender="Male";
        }else if(rdoFemale.isSelected()){
            gender="Female";
        }else{
            gender="";
        }
        String designations=String.valueOf(cmbCourse.getSelectedItem());
        Date dob=Date.valueOf(txtDOB.getText());
        
        String departments=String.valueOf(jComboBox1.getSelectedItem());
       
        
        employee s=new employee(sID, firstName, lastName, gender, designations,departments,dob);
        boolean result=sDB.add(s);
        if(result){
             JOptionPane.showMessageDialog(this, "New employee record is added");
        }else{
            JOptionPane.showMessageDialog(this, "New employee record is not added");
        }
        
        txtStudentID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        rdoMale.setSelected(false);
        rdoFemale.setSelected(false);
        cmbCourse.setSelectedIndex(0);
        txtDOB.setText("");
        jComboBox1.setSelectedIndex(0);
       }
        
       
        
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllActionPerformed
        // TODO add your handling code here:
     // txtDisplay.setText("");
      ArrayList<employee> sList=sDB.getAll(); 
      tblModel.setRowCount(0);
      sList.forEach((s) -> {
          int sID=s.getsID();
          String firstName=s.getFirstName();
          String lastName=s.getLastName();
          String gender=s.getGender();
          String designations=s.getDesignations();
          String departments=s.getDepartments();
          Date dob=s.getDob();
          tblModel.addRow(new Object[]{sID,firstName,lastName,gender,designations,departments,dob});
          //  txtDisplay.append(line+"\n");
        });
    }//GEN-LAST:event_btnGetAllActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        int sID=Integer.valueOf(JOptionPane.showInputDialog("Enter employee ID:"));
        employee s=sDB.get(sID);
        if(s!=null){
            txtStudentID.setText(String.valueOf(s.getsID()));
            txtFirstName.setText(s.getFirstName());
            txtLastName.setText(s.getLastName());
            if(s.getGender().equals("Male")){
                rdoMale.setSelected(true);
            }else{
                rdoFemale.setSelected(true);
            }
            cmbCourse.setSelectedItem(s.getDesignations());
            txtDOB.setText(String.valueOf(s.getDob()));
            jComboBox1.setSelectedItem(s.getDepartments());
        }else{
            JOptionPane.showMessageDialog(this, "The record is not found");
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int sID=Integer.valueOf(JOptionPane.showInputDialog("Enter employee ID:"));
         boolean deleted=sDB.delete(sID);
         if(deleted){
             JOptionPane.showMessageDialog(this, "The record is deleted");
         }else{
             JOptionPane.showMessageDialog(this, "The record is not deleted");
         }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(checkvalidation()){
            int sID=Integer.valueOf(txtStudentID.getText());
        String firstName=txtFirstName.getText();
        String lastName=txtLastName.getText();
        String gender="";
        if(rdoMale.isSelected()){
            gender="Male";
        }else if(rdoFemale.isSelected()){
            gender="Female";
        }else{
            gender="";
        }
        String designations=String.valueOf(cmbCourse.getSelectedItem());
        Date dob=Date.valueOf(txtDOB.getText());
         String departments=String.valueOf(jComboBox1.getSelectedItem());
        
        
        employee s=new employee(sID, firstName, lastName, gender, designations,departments,dob);
        boolean result=sDB.update(s);
        if(result){
             JOptionPane.showMessageDialog(this, "The employee record is updated");
        }else{
            JOptionPane.showMessageDialog(this, "The employee record is not updated");
        }        
       
       } 
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void cmbCourseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmbCourseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseAncestorAdded

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmployeeUI().setVisible(true);
        });
    }
    
    private boolean checkvalidation(){      
        
        if(txtStudentID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "employee ID cannot be blank");
            return false;
        }
        
        try{
            
            int sID=Integer.valueOf(txtStudentID.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "employee Id must be numeric");
            return false;
        }
        
        
        if(txtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "First Name cannot be blank");
            return false;
        }
        
        if(txtLastName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Last Name cannot be blank");
            return false;
        }
        
        if(txtDOB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Date of Birth cannot be blank");
            return false;
        }
        
        try{
            Date dob=Date.valueOf(txtDOB.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Date must be YYYY-MM-DD format");
            return false;
        }
        
         return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnGetAll;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
